[package]
name = "near-token-common"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
serde.workspace = true
near-sdk.workspace = true
hex.workspace = true
