name: Aurora Native ERC-20 Connector

on: [push, pull_request]

jobs:
  rust:
    name: Rust components
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check
        run: make check

  solidity:
    name: Solidity components
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Pull library deps
        run: forge update

      - name: Run forge tests
        working-directory: aurora-locker
        run: forge test

      - name: Run forge fmt
        working-directory: aurora-locker
        run: forge fmt --check
